### PR TITLE
Fix for Issue #3: Encode of Decode with alignment stuffing returns io…

### PR DESCRIPTION
**Pull request by marc-ostrow**
…bit.ErrOverflow

### CODE REVIEW

**Comment by marc-ostrow** [comment]
I could do that sure.

**Comment by marc-ostrow** [comment]
@blahspam Is this test case okay?

**Comment by blahspam** [comment]
@marc-ostrow Thanks for the tests. They really helped me better understand what was going on and inspired a slightly larger change that would ensure binaries with alignment stuffing are re-encoded properly (without the unexpected changes revealed by your test)

Take a look at [my changes](https://github.com/Comcast/scte35-go/tree/bugfix/issue-3) and let me know what you think. 

If everything look good to you, I'll merge that branch and cut a new release.

**Comment by marc-ostrow** [comment]
@blahspam I was indeed a bit dismayed that an encode of a decode were not the same.  You've fixed that.  I like it, so much better.  You'll want to perform a go mod tidy to remove the dependency I added to diff two SpliceInfoSections, which is no longer referenced.

**Pull request merged**
